machines:
  - name: 10.0.1.252
    icmp: yes
    snmp: yes
    web: yes
  - name: 10.0.1.1
    node: yes
    kvm: yes
  - name: 10.0.1.2
    icmp: yes
  - name: google.com
    webs: yes
  - name: 10.0.1.200
    docker: yes
    node: yes
  - name: 10.0.1.30
    node: yes

blackbox_exporter_ip: 10.0.1.200
snmp_exporter_ip: 10.0.1.200

# demoed services and exporters ports
service_port: 9001
blackbox_exporter_port: 9002
snmp_exporter_port: 9003
grafana_port: 9004

# already existing ports
node_exporter_port: 9100
docker_exporter_port: 9323
kvm_exporter_port: 9177

# conf dirs and paths
conf_dir: /conf/demo
data_dir: "{{ conf_dir }}/data"
grafana_data_dir: "{{ conf_dir }}/grafana"

grafana_owner: 472
